from functools import partial
from typing import Any, Protocol, TypeVar, cast, runtime_checkable

T = TypeVar("T")


@runtime_checkable
class ArrayLike(Protocol):
    def __add__(self, other: Any) -> ArrayLike: ...
    def __mul__(self, other: Any) -> ArrayLike: ...
    def sum(self, axis: Any = None) -> ArrayLike: ...
    def mean(self, axis: Any = None) -> ArrayLike: ...
    def __getitem__(self, key: Any) -> ArrayLike: ...
    @property
    def shape(self) -> Any: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: Any) -> AwkwardLike: ...
    def __ne__(self, other: Any) -> AwkwardLike: ...


@runtime_checkable
class AwkwardLike(ArrayLike, Protocol):
    @property
    def fields(self) -> list[str]: ...
    def to_parquet(self, path: str) -> None: ...
    def __lt__(self, other: Any) -> AwkwardLike: ...
    def __le__(self, other: Any) -> AwkwardLike: ...
    def __gt__(self, other: Any) -> AwkwardLike: ...
    def __ge__(self, other: Any) -> AwkwardLike: ...
    @property
    def layout(self) -> Any: ...


asArrayLike = partial(cast, ArrayLike)
asAwkwardLike = partial(cast, AwkwardLike)
